name: mangabaka_app
description: "Official MangaBaka mobile app"
publish_to: 'none'
version: 0.2.3+11


environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  android_intent_plus: ^5.1.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  intl: ^0.20.2
  share_plus: ^13.0.0
  flutter_dotenv: ^6.0.0
  flutter_appauth: ^12.0.0
  flutter_secure_storage: ^8.1.0
  drift: ^2.32.1
  path: ^1.9.1
  path_provider: ^2.1.5
  app_links: ^6.3.2
  crypto: ^3.0.6
  win32_registry: ^3.0.3
  sqlite3_flutter_libs: ^0.6.0+eol
  logging: ^1.3.0
  meta: ^1.16.0
  get_it: ^7.6.0
  mobile_scanner: ^7.2.0
  permission_handler: ^11.3.1
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.4.7
  cached_network_image: ^3.4.1
  window_manager: ^0.4.3
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  vector_math: ^2.2.0
  device_info_plus: ^13.1.0
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.32.1
  build_runner: ^2.13.1
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.9
  sqlite3: ^3.3.1




flutter_native_splash:
  color: "#0a0a0a"
  image: assets/mangabaka512.png
  
  android_12:
    image: assets/mangabaka512.png
    color: "#0a0a0a"
    
  android: true
  ios: true

flutter:
  assets:
    - .env
    - assets/lang/
    - assets/mangabaka512.png
    - assets/series_222_cover.jpg
  uses-material-design: true

msix_config:
  display_name: MangaBaka
  publisher_display_name: Oazzies
  identity_name: dev.oazzies.mangabaka
  publisher: "CN=MangaBaka Organization"
  logo_path: assets/mangabaka512.png
  capabilities: internetClient
